security:

    providers:
        my_db_provider:
            entity:
                class: AppBundle:User
                property: email


    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 13

    role_hierarchy:
        ROLE_ADMIN: [ROLE_SELLER, ROLE_BUYER]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/(admin|cabinet)
            anonymous: ~
            provider: my_db_provider
            simple_form:
                login_path: /admin/login
                check_path: /admin/login_check
                authenticator: AppBundle\Security\PasswordAuthenticator
            logout:
                path: /admin/logout
                target: /admin/login

    access_control:
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/cabinet, role: [ROLE_SELLER, ROLE_BUYER] }